### ISSUE TITLE
Insert row / delete row 

### ISSUE THREAD

**Issue by Charuka2370** [JDMCreator/LaTeXTableEditor#63] opened 2022-05-13 13:01 UTC
This function does not work properly

**Comment by dthuremella** [comment] 2022-05-16 11:52
can't insert a  full column next to a colum that starts with a multirow

**Comment by dthuremella** [comment] 2022-05-18 15:50
When I have a header row where where columns are merged for that row and I
try to add another column, it automatically merges the top row of that
column as well, which is not what I want.

**Comment by JDMCreator** [comment] 2023-01-03 04:08
This is intended behaviour.

**Closed** 2023-07-31 14:50 UTC
