### ISSUE TITLE
LaTeX table import fails on commented `%\begin{tabular}`

### ISSUE THREAD

**Issue by gcr** [JDMCreator/LaTeXTableEditor#90] opened 2023-12-07 15:31 UTC
The editor fails to import LaTeX that contains a commented `\begin` command.

Minimal example:
```latex
\begin{tabular}[ht]
%\begin{tabular}[ht]
a & b & c \\
d & e & f \\
g & g & i
\end{tabular}
```

The following works:
```latex
\begin{tabular}[ht]
a & b & c \\
d & e & f \\
g & g & i
\end{tabular}
```

Thanks for the great product!

**Comment by JDMCreator** [comment] 2024-02-17 21:45
Confirmed that there's issue with commenting a tabular/table environment. However, your LaTeX is invalid and won't be loaded by the editor.

**Comment by JDMCreator** [comment] 2024-02-17 21:56
Duplicate of #87

**Closed** 2024-02-17 22:24 UTC
Labels: Type: bug, Priority: Low, Status: In Development
