### ISSUE TITLE
Microsoft Edge rendering

### ISSUE THREAD

**Issue by levoniaz** [JDMCreator/LaTeXTableEditor#1] opened 2017-07-05 22:49 UTC
Just in case it's helpful, I popped `http://www.latex-tables.com/preview/` open in Microsoft Edge.  

`Microsoft Edge 38.14393.1066.0`
`Microsoft EdgeHTML 14.14393`

Screenshot captured below. 

![LaTeX-Table-Editor-Screenshot](https://user-images.githubusercontent.com/7253380/27888089-35e515fa-61b2-11e7-99e8-5d07906cf74b.PNG)

May be reasonable to object to unsupported browsers explicitly.

**Comment by JDMCreator** [comment] 2017-07-08 16:20
Hi,

There seems to be two issues here : a rendering problem with the title because of your screen resolution and an issue with Edge.

Edge will be a supported browser with Chrome and Firefox, so I'll be working on this issue. The rendering problem caused by the screen resolution is solved and the fix will be part of the next preview.

**Comment by JDMCreator** [comment] 2017-08-14 22:19
Fixed the empty cell bug in Edge in v 0.2. I'm working on a crossbrowser solution to access the same HTML for each browser. It will part of v 0.3. Then, I'll be able to close this issue.

**Closed** 2018-05-30 02:48 UTC
Labels: Type: bug
